#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef-client', "=1.1.2"
cookbook 'apache2'
cookbook 'apt'
cookbook 'mysql'
cookbook 'memcached'
cookbook 'php'
cookbook 'redis'
cookbook 'xml'
cookbook 'xslt'
cookbook 'nginx'
cookbook 'redisio', :git => 'git://github.com/brianbianco/redisio.git'
cookbook 'git'
cookbook 'users'
cookbook 'nodejs'
cookbook 'build-essential'
cookbook 'imagemagick'

# ODI books here
#cookbook 'rvm', :git => 'git://github.com/theodi/chef-rvm.git'
cookbook 'rvm', :git => 'git@github.com:theodi/chef-rvm.git'
cookbook 'libcurl', :git => 'git@github.com:theodi/chef-libcurl.git'
cookbook 'sqlite', :git => 'git@github.com:theodi/chef-sqlite.git'
cookbook 'envbuilder', :git => 'git@github.com:theodi/chef-envbuilder.git'