#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef-client', "=1.1.2"
cookbook 'apache2'
cookbook 'apt'
cookbook 'mysql'
cookbook 'memcached'
cookbook 'php'

cookbook 'redis'
cookbook 'xml'
cookbook 'xslt'
cookbook 'nginx'
cookbook 'redisio', :git => 'git://github.com/brianbianco/redisio.git'
cookbook 'git'
cookbook 'rvm', :git => 'https://github.com/fnichol/chef-rvm'
cookbook 'users'
