#!/usr/bin/env ruby
#^syntax detection

ecosystem "superawesome" do

  container "superawesomeserver" do
    distro "ubuntu"
    release "lucid"
    persist true
    ip "192.168.0.1"
    mac "00:00:5e:35:ea:d5"
    chef_client ({ :environment => "cucumber",
                   :run_list    => [
                       "role[base]"
                   ]
    })
  end

end
