#!/usr/bin/env ruby
#^syntax detection

ecosystem "odi" do

  container "env-test" do
    distro "ubuntu"
    release "lucid"
    persist true
#    ip "192.168.32.100"
#    mac "00:00:5e:d1:fa:08"
    chef_client ({ :environment => "vagrant",
                   :run_list    => [
                       "recipe[envbuilder]"
                   ]
    })
  end
end
